name: banana_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  ultralytics_yolo: ^0.1.37
  image: ^4.1.7
  image_picker: ^1.2.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  permission_handler: ^12.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/best_float32.tflite
